spring.application.name=spots-api

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/hackathon
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# ===============================
# Logging Configuration
# ===============================

# Application logging level
logging.level.com.sioma.spotsapi=DEBUG

# For Spring Web (useful for debugging HTTP requests)
logging.level.org.springframework.web=DEBUG

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===============================
# LOGGING MDC
# ===============================
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %clr([%thread]){faint} %clr([%X{requestId}]){magenta} %clr([%X{userId:-system}]){yellow} %clr([%X{method:-} %X{uri:-}]){faint} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===============================
# IntelliJ console colors
# ===============================
spring.output.ansi.enabled=always

# ===============================
# SERVER
# ===============================
server.port=8080